name: lapalma-earthquakes
channels:
  - conda-forge
  - default
dependencies:
  - numpy
  - matplotlib
  - pandas
  - ipykernel
  - jupyterlab
  - scipy
  - seaborn
  - altair
  - plotly
  - pip
  - pip:
      - -e ..
